### ISSUE TITLE
You are able to overwrite any of your previous move, therefore giving you the ability to skip a move.

### ISSUE THREAD

**Issue by nerdkid50** [m4ngoroot/Tic-Tac-Toe#3]

**Comment by nerdkid50** [comment]
You can assign this to me if you'd like.

**Comment by m4ngoroot** [comment]
fixed the issue,
    currently trying to implement a minmax algortithm just starting and following this tutorial https://www.youtube.com/watch?v=fT3YWCKvuQE if you would like to contribute with this

**Comment by nerdkid50** [comment]
Sounds good.
